<a href="https://colab.research.google.com/github/nkefeyan-22-26/ECON5200-Applied-Data-Analytics-in-Economics/blob/main/MidtermProject/data/raw/notebooks/01_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning

In [1]:
!pip install pyreadstat pandas numpy

Collecting pyreadstat
  Downloading pyreadstat-1.3.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pyreadstat-1.3.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 77.4 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.3.3

In [3]:
import pandas as pd
import pyreadstat
import os

In [4]:
sas7bdat_FILEPATH = "/content/drive/MyDrive/ECON5200/Midterm Project/m_d_806.sas7bdat"
df = pd.read_sas(sas7bdat_FILEPATH)
df.head()

,STATE,SEXK,AGEK,QTRBKID,RACEK,SPANISH,BIRTHPLK,SCHOOLK,GRADE,FINGRADE,...,FINGRADD,CLASSD,WEEKSD,HOURSD,INCOME1D,INCOME2D,AWEEK79D,AHOUR79D,AINC1D,AINC2D
0,b'01',b'1',b'09',b'3',b'01',b'0',b'001',b'1',b'06',b'1',...,b'2',b'1',b'52',b'40',b'28005',b'00000',b'0',b'0',b'0',b'0'
1,b'01',b'1',b'08',b'3',b'01',b'0',b'001',b'2',b'05',b'1',...,b'2',b'5',b'52',b'72',b'00000',b'10005',b'0',b'0',b'0',b'3'
2,b'01',b'0',b'09',b'1',b'01',b'0',b'001',b'1',b'05',b'1',...,b'2',b'5',b'16',b'48',b'00000',b'16005',b'0',b'0',b'2',b'0'
3,b'01',b'0',b'05',b'2',b'01',b'0',b'001',b'1',b'02',b'1',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,b'01',b'1',b'11',b'1',b'01',b'0',b'001',b'1',b'07',b'1',...,b'2',b'1',b'32',b'40',b'09925',b'00000',b'0',b'0',b'3',b'3'

In [5]:
# Check raw file size
raw_size = os.path.getsize("/content/drive/MyDrive/ECON5200/Midterm Project/m_d_806.sas7bdat")
print(f"Raw SAS file: {raw_size / 1_000_000:.1f} MB")

# Check dataframe memory usage
print(f"\nDataframe shape: {df.shape}")
print(f"Dataframe memory usage: {df.memory_usage(deep=True).sum() / 1_000_000:.1f} MB")

df.head()

Raw SAS file: 189.9 MB

Dataframe shape: (927267, 85)
Dataframe memory usage: 2946.4 MB

,STATE,SEXK,AGEK,QTRBKID,RACEK,SPANISH,BIRTHPLK,SCHOOLK,GRADE,FINGRADE,...,FINGRADD,CLASSD,WEEKSD,HOURSD,INCOME1D,INCOME2D,AWEEK79D,AHOUR79D,AINC1D,AINC2D
0,b'01',b'1',b'09',b'3',b'01',b'0',b'001',b'1',b'06',b'1',...,b'2',b'1',b'52',b'40',b'28005',b'00000',b'0',b'0',b'0',b'0'
1,b'01',b'1',b'08',b'3',b'01',b'0',b'001',b'2',b'05',b'1',...,b'2',b'5',b'52',b'72',b'00000',b'10005',b'0',b'0',b'0',b'3'
2,b'01',b'0',b'09',b'1',b'01',b'0',b'001',b'1',b'05',b'1',...,b'2',b'5',b'16',b'48',b'00000',b'16005',b'0',b'0',b'2',b'0'
3,b'01',b'0',b'05',b'2',b'01',b'0',b'001',b'1',b'02',b'1',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,b'01',b'1',b'11',b'1',b'01',b'0',b'001',b'1',b'07',b'1',...,b'2',b'1',b'32',b'40',b'09925',b'00000',b'0',b'0',b'3',b'3'

Method 1

In [8]:
# Step 2: Downcast the data types to shrink the size
# SAS files often load every number as a 64-bit float even when it doesn't need to be. This alone can cut your file size dramatically:
def optimize_df(df):
    for col in df.select_dtypes(include=['float64']).columns:
        df[col] = pd.to_numeric(df[col], downcast='float')
    for col in df.select_dtypes(include=['int64']).columns:
        df[col] = pd.to_numeric(df[col], downcast='integer')
    return df

df_optimized = optimize_df(df.copy())

print(f"Before: {df.memory_usage(deep=True).sum() / 1_000_000:.1f} MB")
print(f"After:  {df_optimized.memory_usage(deep=True).sum() / 1_000_000:.1f} MB")

Before: 2946.4 MB
After:  2909.3 MB

In [10]:
print(df.columns.tolist())

['STATE', 'SEXK', 'AGEK', 'QTRBKID', 'RACEK', 'SPANISH', 'BIRTHPLK', 'SCHOOLK', 'GRADE', 'FINGRADE', 'ASEX', 'AAGE', 'AQTRBRTH', 'ABIRTHPL', 'ASCHOOL', 'AYEARSCH', 'AFINGRAD', 'YOBK', 'AGEQK', 'SEX2ND', 'RACE2ND', 'SPAN2ND', 'SCH2ND', 'GRADE2ND', 'FIN2ND', 'ASEX2ND', 'AAGE2ND', 'AQTR2ND', 'ASCH2ND', 'AYEAR2ND', 'AFIN2ND', 'AGEQ2ND', 'SEX3RD', 'AGEQ3RD', 'SEX4TH', 'AGEQ4TH', 'SEX5TH', 'AGEQ5TH', 'TWIN1ST', 'TRIPLET', 'KIDCOUNT', 'FAMINC', 'AGEM', 'QTRBTHM', 'MARITAL', 'RACEM', 'SPANISHM', 'FERT', 'TIMESMAR', 'AGEMAR', 'QTRMAR', 'WIDOW', 'GRADEM', 'FINGRADM', 'CLASSM', 'WEEKSM', 'HOURSM', 'INCOME1M', 'INCOME2M', 'INCOME6M', 'POVERTY', 'AFERTIL', 'AWEEK79M', 'AHOUR79M', 'AINC1M', 'AINC2M', 'YOBM', 'AGED', 'QTRBTHD', 'RACED', 'SPANISHD', 'TIMEMARD', 'AGEMARD', 'QTRMARD', 'GRADED', 'FINGRADD', 'CLASSD', 'WEEKSD', 'HOURSD', 'INCOME1D', 'INCOME2D', 'AWEEK79D', 'AHOUR79D', 'AINC1D', 'AINC2D']

In [12]:
# Keep only the columns that are relevant to Angrist & Evans replication.
# This is essential because the raw data is far too large to process
# Core variables for Angrist & Evans replication
# Angrist & Evans variables mapped to YOUR actual column names
cols_to_keep = [
    # Instrument & key regressors
    'SEXK',       # sex of first child (boy1st)
    'SEX2ND',     # sex of second child (boy2nd)
    'KIDCOUNT',   # number of kids (used to construct morekids)

    # Mother characteristics
    'AGEM',       # mother's age
    'RACEM',      # mother's race
    'SPANISHM',   # mother hispanic
    'GRADEM',     # mother's education
    'MARITAL',    # marital status

    # Mother's labor supply outcomes
    'WEEKSM',     # weeks worked by mother
    'HOURSM',     # hours worked by mother
    'INCOME1M',   # mother's wage income
    'INCOME2M',   # mother's other income

    # Father/spouse characteristics & labor supply
    'AGED',       # father's age
    'RACED',      # father's race
    'GRADED',     # father's education
    'WEEKSD',     # weeks worked by father
    'HOURSD',     # hours worked by father
    'INCOME1D',   # father's wage income

    # Household
    'FAMINC',     # family income
    'STATE',      # state
]

# Only keep columns that actually exist
cols_existing = [c for c in cols_to_keep if c in df.columns]
print(f"Keeping {len(cols_existing)} of {len(df.columns)} columns")

df_slim = df[cols_existing].copy()
print(f"Slim dataframe memory: {df_slim.memory_usage(deep=True).sum() / 1_000_000:.1f} MB")

Keeping 20 of 85 columns
Slim dataframe memory: 758.3 MB

In [13]:
df_slim.to_csv("/content/census80_slim.csv.gz", index=False, compression='gzip')

import os
size = os.path.getsize("/content/census80_slim.csv.gz")
print(f"Final file size: {size / 1_000_000:.1f} MB")

Final file size: 13.7 MB

Method 2

In [14]:
# Step 1: Convert low-cardinality columns to category dtype
for col in df.columns:
    n_unique = df[col].nunique()
    if n_unique < 50:  # if a column has fewer than 50 unique values, make it categorical
        df[col] = df[col].astype('category')
        print(f"{col}: {n_unique} unique values → category")

# Step 2: Downcast all remaining numeric columns
for col in df.select_dtypes(include=['float64']).columns:
    df[col] = pd.to_numeric(df[col], downcast='float')
for col in df.select_dtypes(include=['int64']).columns:
    df[col] = pd.to_numeric(df[col], downcast='integer')

print(f"\nOptimized memory usage: {df.memory_usage(deep=True).sum() / 1_000_000:.1f} MB")

SEXK: 2 unique values → category
AGEK: 17 unique values → category
QTRBKID: 4 unique values → category
RACEK: 13 unique values → category
SPANISH: 5 unique values → category
SCHOOLK: 4 unique values → category
GRADE: 20 unique values → category
FINGRADE: 4 unique values → category
ASEX: 1 unique values → category
AAGE: 2 unique values → category
AQTRBRTH: 2 unique values → category
ABIRTHPL: 4 unique values → category
ASCHOOL: 3 unique values → category
AYEARSCH: 3 unique values → category
AFINGRAD: 3 unique values → category
YOBK: 18 unique values → category
SEX2ND: 2 unique values → category
RACE2ND: 13 unique values → category
SPAN2ND: 5 unique values → category
SCH2ND: 4 unique values → category
GRADE2ND: 17 unique values → category
FIN2ND: 4 unique values → category
ASEX2ND: 1 unique values → category
AAGE2ND: 2 unique values → category
AQTR2ND: 2 unique values → category
ASCH2ND: 3 unique values → category
AYEAR2ND: 3 unique values → category
AFIN2ND: 3 unique values → category
SEX3RD: 2 unique values → category
SEX4TH: 2 unique values → category
SEX5TH: 2 unique values → category
TWIN1ST: 2 unique values → category
TRIPLET: 1 unique values → category
KIDCOUNT: 12 unique values → category
AGEM: 41 unique values → category
QTRBTHM: 4 unique values → category
MARITAL: 5 unique values → category
RACEM: 13 unique values → category
SPANISHM: 5 unique values → category
FERT: 12 unique values → category
TIMESMAR: 3 unique values → category
AGEMAR: 49 unique values → category
QTRMAR: 5 unique values → category
WIDOW: 3 unique values → category
GRADEM: 23 unique values → category
FINGRADM: 4 unique values → category
CLASSM: 8 unique values → category
POVERTY: 7 unique values → category
AFERTIL: 2 unique values → category
AWEEK79M: 3 unique values → category
AHOUR79M: 2 unique values → category
AINC1M: 3 unique values → category
AINC2M: 3 unique values → category
YOBM: 42 unique values → category
QTRBTHD: 4 unique values → category
RACED: 13 unique values → category
SPANISHD: 5 unique values → category
TIMEMARD: 2 unique values → category
QTRMARD: 4 unique values → category
GRADED: 23 unique values → category
FINGRADD: 4 unique values → category
CLASSD: 8 unique values → category
AWEEK79D: 3 unique values → category
AHOUR79D: 2 unique values → category
AINC1D: 3 unique values → category
AINC2D: 3 unique values → category

Optimized memory usage: 642.8 MB

In [15]:
# Step 3: Save locally with maximum gzip compression
# compression level 9 is the slowest but smallest possible file
df.to_csv("/content/census80_full.csv.gz",
          index=False,
          compression={'method': 'gzip', 'compresslevel': 9})

size = os.path.getsize("/content/census80_full.csv.gz")
print(f"Final file size: {size / 1_000_000:.1f} MB")

Final file size: 37.5 MB